### ISSUE TITLE
table tr hover 颜色都是浅紫色， 没有根据主题色变化

### ISSUE THREAD

**Issue by cynthiawan** [luffyZh/dynamic-antd-theme#1]
table tr hover 颜色都是浅紫色， 没有根据主题色变化
![image](https://user-images.githubusercontent.com/12509112/59817622-432b7180-9353-11e9-87b7-6a83e9c1a5f7.png)

**Comment by luffyZh** [comment]
已修复，请更新版本至 v0.2.0。谢谢Issue🙏

![图片](https://user-images.githubusercontent.com/17840558/59823613-49284f00-9361-11e9-862e-2c3c7a374478.png)
