### ISSUE TITLE
datePicker样式不兼容

### ISSUE THREAD

**Issue by fangkyi03** [luffyZh/dynamic-antd-theme#10]

**Comment by luffyZh** [comment]
@fangkyi03 描述的详细一些。。。如果能给个图片就更好了

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/67938389-548e5f80-fc0a-11e9-9123-466e652669d7.png)
![image](https://user-images.githubusercontent.com/30390014/67938409-5e17c780-fc0a-11e9-9987-c0bb9c80a8b0.png)

**Comment by luffyZh** [comment]
@fangkyi03 
已修复，请更新到0.3.6，谢谢issue~
![图片](https://user-images.githubusercontent.com/17840558/67998078-f60cc400-fc91-11e9-9f47-51ccb615d516.png)
