### ISSUE TITLE
支持其他变量的自定义吗 比如@layout-header-background @font-size-base 这些

### ISSUE THREAD

**Issue by yinminqian** [luffyZh/dynamic-antd-theme#101]
以下antd的主题支持么 
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

**Comment by luffyZh** [comment]
@yinminqian 暂时不支持，但是可以通过 custom css 的方式逐个覆盖

**Comment by luffyZh** [comment]
@yinminqian 更多讨论交流可以加我微信 zhoudeyou945
