### ISSUE TITLE
日历显示有问题

### ISSUE THREAD

**Issue by LXIACHUA** [luffyZh/dynamic-antd-theme#11]
切换month和year的部分主题色没有切换
<img width="326" alt="企业微信截图_20191115094335" src="https://user-images.githubusercontent.com/42471384/68910378-86680000-078c-11ea-904a-f6e0fefc8bb3.png">

**Comment by luffyZh** [comment]
@LXIACHUA 给个gif？或者给个demo仓库，我这边，month,week,range都没有问题。。。可能某些特定操作导致的，这张截图没太理解～

**Comment by luffyZh** [comment]
@LXIACHUA 特意看了下，你说的是日历组件。。。sorry啊，明天我修复一下～

**Comment by luffyZh** [comment]
@LXIACHUA 已修复，感谢issue，请更新到v0.3.8.
