### ISSUE TITLE
表格覆盖样式未同步

### ISSUE THREAD

**Issue by xiaohuwei** [luffyZh/dynamic-antd-theme#12]
切换主题配色后 其他的都正常 表格的hover样式还是没有变过来 

![](https://cdn.xiaohuwei.cn/7401e594a29f63298350272342c87e7d)

**Comment by xiaohuwei** [comment]
"antd": "^3.20.0",
"dynamic-antd-theme": "^0.3.6",

**Comment by xiaohuwei** [comment]
看到更新日志好像这条记录 估计还没做高版本的适配😂

**Comment by xiaohuwei** [comment]
看到更新日志好像有这条记录 估计还没做高版本的适配😂

**Comment by luffyZh** [comment]
@xiaohuwei 感谢感谢，我看了一下，确实table的hover类发生变化了，这边升级一下0.3.7试试～如果有其他问题欢迎继续提👏～
