### ISSUE TITLE
主题发生改变后 树状表格展开的icon样式未变化

### ISSUE THREAD

**Issue by xiaohuwei** [luffyZh/dynamic-antd-theme#13]
```
"antd": "^3.20.0",
"dynamic-antd-theme": "^0.3.8",
```
![](https://cdn.xiaohuwei.cn/2d70bfe2e52f7d4920bea8d190e063f6)

**Comment by xiaohuwei** [comment]
也是 覆盖样式

**Comment by luffyZh** [comment]
@xiaohuwei 感谢感谢，希望继续使用，帮助改进～已修复，更新到最新版～
![图片](https://user-images.githubusercontent.com/17840558/69507830-f5a0d980-0f6e-11ea-9413-5665db576c49.png)
