### ISSUE TITLE
希望加入对TS的支持

### ISSUE THREAD

**Issue by xiaohuwei** [luffyZh/dynamic-antd-theme#14]
![](https://cdn.xiaohuwei.cn/11eeafd18e3b99d89e8edc80878e26fe)

**Comment by xiaohuwei** [comment]
作者如果有空可以改改 😂 这个画波浪线有点难受

**Comment by luffyZh** [comment]
@xiaohuwei 之前也有人提了一下，我就简单的生成了一个TS声明文件，没有去尝试。最近有点忙，可能暂时没什么时间～
这个issue先保留～等支持了的～再告诉你

**Comment by xiaohuwei** [comment]
ok
