### ISSUE TITLE
changeAntdTheme事件改变配色 调色板未同步发生改变

### ISSUE THREAD

**Issue by xiaohuwei** [luffyZh/dynamic-antd-theme#15]
![](https://cdn.xiaohuwei.cn/2f6722a8e55c7e1bb32f1af7399432bf)

**Comment by xiaohuwei** [comment]
还有一个问题就是 changeAntdTheme 事件发生后本地缓存未更新 需要手动更新 
![](https://cdn.xiaohuwei.cn/29d3f86ec95e4a57d5cbcb8cc5220619)

**Comment by luffyZh** [comment]
@xiaohuwei emm，如果你使用了color-picker那么应该直接使用这个组件<DynamicAntdTheme />而不是方法去改变主题。
P.S.因为这两个方法是给不想要使用color-picker的同学，想要自己配置改变主题的按钮的需求设计的。
Issue在这里 -> [Issue](https://github.com/luffyZh/dynamic-antd-theme/issues/4)
所以可能这里就不修复了，场景不同。或者如果真的有这种需要的场景？可以继续讨论
