### ISSUE TITLE
Add the demo code in example folder

### ISSUE THREAD

**Issue by renjiie** [luffyZh/dynamic-antd-theme#16]
Hi,
Appreciate your great effort for this wonderful package. Could you add the demo code in a folder called "example" ,  its better to have all the example codes in a seperate  __example__ folder. It will be easy to follow the example by the developers also .

Thanks.

**Comment by luffyZh** [comment]
Thank you for your affirmation and advice. That's a good idea add a demo folder for users to use.
The folder is created called `examples` and i'm update the online demo. Hope it's helpful for u.

https://dynamic-antd-theme.luffyzh.now.sh/

<img width="1415" alt="图片" src="https://user-images.githubusercontent.com/17840558/69771640-7f97af00-11c8-11ea-9211-df5441514370.png">

**Comment by renjiie** [comment]
The new demo looks super cool. Great work @luffyZh ..
