### ISSUE TITLE
Support Font Family and other props.

### ISSUE THREAD

**Issue by sebas-deedee** [luffyZh/dynamic-antd-theme#21]
Is there a way to change font-family and other variables?
Are you planning to support this in the future?

**Comment by luffyZh** [comment]
@sebas-deedee Did you mean change the font-family of ant-design? Can you give me some case why you need change the font-family.

**Comment by luffyZh** [comment]
@sebas-deedee 
Hello, I've come up with a solution to your problem. U can leave a message if you have any other questions.
U can see there:
https://github.com/luffyZh/dynamic-antd-theme#define-custom-css
