### ISSUE TITLE
关于二次封装的组件的样式换肤问题。

### ISSUE THREAD

**Issue by liuzhangren** [luffyZh/dynamic-antd-theme#28]
我这边的组件库是基于antd 3.0 版本的组件二次封装的，引用该组件换肤大部分颜色可以置换，二次封装过的组件修改过颜色 无法换色，求给点思路和解决方案

**Comment by luffyZh** [comment]
@liuzhangren 二次封装的，然后使用了自定义的类？

 - 第一种：在换肤的时候，调用changeCallback函数，把封装的组件样式手动修改一下

 - 第二种：在customCss里把该组件颜色类提前覆盖掉。参考[customCss](https://github.com/luffyZh/dynamic-antd-theme#how-to-use-the-primarycolors-in-customcss)

上面两种应该都是可以的，第二种可能更方便，但是需要更新到最新版。前提是二次封装的组件有能控制和操作的id或者class。

**Comment by liuzhangren** [comment]
可行，给你点个star，挺方便的不用官方的还去配那么多配置。 给力
