### ISSUE TITLE
antd4.6.x下部分组件的颜色未随动态更改

### ISSUE THREAD

**Issue by luox12** [luffyZh/dynamic-antd-theme#35]
目前发现的两个组件：
Tabs：active的TabPane页头
Select: 边框颜色、被选中的Option的背景色

**Comment by luffyZh** [comment]
@luox12 感谢感谢，好久没更新了，随时提哈～改完我会同步

**Comment by luffyZh** [comment]
@luox12 非常感谢，已经 Fix，可以更新最新版，还有就是如果遇到了，随时提～
![图片](https://user-images.githubusercontent.com/17840558/97774344-ec15ed80-1b91-11eb-9c0e-f67c8a69fb66.png)
