### ISSUE TITLE
antd版本为4.8.0，RangePicker颜色没有生效

### ISSUE THREAD

**Issue by rounrounAng** [luffyZh/dynamic-antd-theme#36]
主题色为红色，
<img width="460" alt="屏幕快照 2020-11-05 12 42 24" src="https://user-images.githubusercontent.com/15197935/98198688-78def380-1f64-11eb-8d99-e13db0a65b1b.png">

但是RangePicker没有生效
![image](https://user-images.githubusercontent.com/15197935/98198582-39b0a280-1f64-11eb-956c-c3c8bf1b2f7f.png)

**Comment by luffyZh** [comment]
已解决，请升级到最新版，感谢反馈～后面有问题随时沟通～
<img width="998" alt="图片" src="https://user-images.githubusercontent.com/17840558/98527591-2da34880-22b6-11eb-999e-e03fa1d8c583.png">
