### ISSUE TITLE
Table中可横向滚动时有问题

### ISSUE THREAD

**Issue by gouding** [luffyZh/dynamic-antd-theme#37]
![11](https://user-images.githubusercontent.com/13016673/98333218-350aed80-203b-11eb-989f-d90116f0b120.gif)

**Comment by luffyZh** [comment]
感谢反馈，已解决，请更新到最新版
![图片](https://user-images.githubusercontent.com/17840558/98535797-acea4980-22c1-11eb-8864-6c441c93ae71.png)
