### ISSUE TITLE
antdv4+ 顶部导航菜单时，鼠标移入菜单，主题颜色不对

### ISSUE THREAD

**Issue by a758801405** [luffyZh/dynamic-antd-theme#38]
antd:  v4.8
系统: macOS v10.15.6
浏览器：chrome v86
问题: 刚进入系统时是正确的，鼠标移入菜单颜色显示不对，比如我设置的颜色是#FF8712，鼠标移入显示的却是#1890ff
如图：
![image](https://user-images.githubusercontent.com/13042895/99178699-c9b6cf00-2750-11eb-9c6e-e6669564f8fd.png)
![image](https://user-images.githubusercontent.com/13042895/99178700-d1767380-2750-11eb-94cb-6d09bf7cc4ab.png)
![image](https://user-images.githubusercontent.com/13042895/99178702-dcc99f00-2750-11eb-8da5-fe432d347ac5.png)

**Comment by luffyZh** [comment]
@a758801405 感谢反馈，4.0以后antd改变了很多新增了很多，可能会有覆盖不全的场景，遇到了随时反馈～都会解决哈。
![图片](https://user-images.githubusercontent.com/17840558/99209085-469f8280-27fd-11eb-8fd6-7ee72c87bccc.png)
升级到最新版就可以了
