### ISSUE TITLE
主题颜色问题

### ISSUE THREAD

**Issue by a758801405** [luffyZh/dynamic-antd-theme#39]
我用的是umi中的qiankun微服务应用，切换到子应用时，你的主题颜色被默认的antd的颜色覆盖了，原因可能是因为子应用的样式优先级更高，不知道这个可以处理吗
![image](https://user-images.githubusercontent.com/13042895/99473332-56e26980-2985-11eb-91dd-ff5114665702.png)

**Comment by luffyZh** [comment]
@a758801405 不确定，但是我觉得应该不是被覆盖，而是子应用可能需要重新注入，就是切换的时候去检测 `<style id="dynamic_antd_theme_custom_style">`标签是否存在，如果不存在，使用 `generateDynamicTheme(color)`去给子应用注入，应该就可以了

**Comment by a758801405** [comment]
没有看到有这个方法generateDynamicTheme，是不是这个generateThemeColor

**Comment by luffyZh** [comment]
嗯，对的，就是看看文档，里面 export 了两个方法，可以根据颜色值重新生成一遍，尝试一下～


| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月18日 19:03，freeMan<notifications@github.com> 写道：

没有看到有这个方法generateDynamicTheme，是不是这个generateThemeColor

**Comment by a758801405** [comment]
试过了，没有用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年11月18日 21:16
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)





 嗯，对的，就是看看文档，里面 export 了两个方法，可以根据颜色值重新生成一遍，尝试一下～
 
 
 | |
 周公子
 |
 |
 zhoudeyou945@126.com
 |
 签名由网易邮箱大师定制
 
 
 在2020年11月18日 19:03，freeMan<notifications@github.com&gt; 写道：
 
 没有看到有这个方法generateDynamicTheme，是不是这个generateThemeColor

**Comment by luffyZh** [comment]
不应该，localstorage存了主应用的颜色了吗，然后在子应用调用后，生成style标签了吗？可以看看截图


| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月18日 21:18，freeMan<notifications@github.com> 写道：

试过了，没有用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年11月18日 21:16
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)





嗯，对的，就是看看文档，里面 export 了两个方法，可以根据颜色值重新生成一遍，尝试一下～


| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月18日 19:03，freeMan<notifications@github.com&gt; 写道：

没有看到有这个方法generateDynamicTheme，是不是这个generateThemeColor

**Comment by a758801405** [comment]
生成了，但是样式被覆盖了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年11月18日 21:20
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)

**Comment by luffyZh** [comment]
好吧，看到了，不因该啊，这个 style 标签放在了所有样式的最下方，应该不会被覆盖。或者是否是加载时机的问题，可以尝试异步调用看看，实在不行的话，可能就得考虑 !important了


| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月18日 21:18，freeMan<notifications@github.com> 写道：

试过了，没有用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年11月18日 21:16
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)





嗯，对的，就是看看文档，里面 export 了两个方法，可以根据颜色值重新生成一遍，尝试一下～


| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月18日 19:03，freeMan<notifications@github.com&gt; 写道：

没有看到有这个方法generateDynamicTheme，是不是这个generateThemeColor

**Comment by luffyZh** [comment]
嗯，明天的吧，我自己弄一个微服务试试，两个应用都用antd了，版本一致对吧，但是切换的时候不生效。我明天试一下～
| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月18日 21:22，freeMan<notifications@github.com> 写道：

生成了，但是样式被覆盖了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年11月18日 21:20
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)

**Comment by a758801405** [comment]
是的，麻烦你了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年11月18日 21:25
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)

**Comment by a758801405** [comment]
异步调用我也试过了，也被覆盖的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年11月18日 21:25
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)





 
 
 嗯，明天的吧，我自己弄一个微服务试试，两个应用都用antd了，版本一致对吧，但是切换的时候不生效。我明天试一下～
 | |
 周公子
 |
 |
 zhoudeyou945@126.com
 |
 签名由网易邮箱大师定制
 
 
 在2020年11月18日 21:22，freeMan<notifications@github.com&gt; 写道：
 
 生成了，但是样式被覆盖了
 
 
 
 发自我的iPhone
 
 
 ------------------ 原始邮件 ------------------
 发件人: luffyZh <notifications@github.com&amp;gt;
 发送时间: 2020年11月18日 21:20
 收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&amp;gt;
 抄送: freeMan <758801405@qq.com&amp;gt;, Mention <mention@noreply.github.com&amp;gt;
 主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)

**Comment by luffyZh** [comment]
@a758801405 不好意思，最近有点忙，能不能给一个仓库，qiankun的例子，然后我去参考一下，看看能不能解

**Comment by a758801405** [comment]
上传了个简单例子，https://github.com/a758801405/yt-admin-main.git

**Comment by luffyZh** [comment]
感谢，但是你是不是忘记写子应用了，我看光注册但是没有任何内容啊


| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月29日 19:25，freeMan<notifications@github.com> 写道：

上传了个简单例子，https://github.com/a758801405/yt-admin-main.git

**Comment by a758801405** [comment]
子应用和主应用项目都要跑起来

**Comment by luffyZh** [comment]
哈哈，好的，我看到了，你只给我主应用的仓库了，我去你github clone子应用的
| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月30日 21:01，freeMan<notifications@github.com> 写道：

子应用和主应用项目都要跑起来

**Comment by a758801405** [comment]
![Uploading image.png…]()

**Comment by luffyZh** [comment]
兄弟，首先问题是，子应用加载的时候，在主应用里增加了一个类似于iframe的块，里面有重新加载了 子应用 antd 的css，所以导致被覆盖了；
其次，通过localStorage的方法，是可以实现子应用的样式同步的，具体如下图，我这边看起来主应用登录成功，点击进入子应用，子应用主题颜色也会发生变化。


<截图见两个附件的gif>，最后的效果就是切换到子应用刷新一下就可以了。不过刷新体验肯定是不好，所以我觉得可能跳转的时候不使用 router 使用 a标签跳转到子应用更合理。我后面会尝试其他办法解决




具体解决方案，我这边有几个：
第一个，可以尝试主子应用跳转的时候携带主题色，然后子应用加载的时候进行覆盖。
第二个，我这边可以尝试看看是否能对微服务乾坤之类的这种模式做优化，动态监听。


我这边最近看看方案，如果有好的解决方案～再跟你同步，就是问题应该是有解的。感谢配合，解决了跟你同步，是能解决的哈
| |
周公子
|
|
zhoudeyou945@126.com
|
签名由网易邮箱大师定制


在2020年11月30日 21:06，freeMan<notifications@github.com> 写道：

**Comment by luffyZh** [comment]
@a758801405 

![图片](https://user-images.githubusercontent.com/17840558/100696227-05e36400-33ce-11eb-9217-f2b938f397e7.png)

gif 图无法上传。。。感兴趣可以加我微信，zhoudeyou945

**Comment by a758801405** [comment]
好的，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luffyZh <notifications@github.com&gt;
发送时间: 2020年12月1日 12:07
收件人: luffyZh/dynamic-antd-theme <dynamic-antd-theme@noreply.github.com&gt;
抄送: freeMan <758801405@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[luffyZh/dynamic-antd-theme] 主题颜色问题 (#39)
