### ISSUE TITLE
能否不通过colorPicker，而是传color来改变主题色

### ISSUE THREAD

**Issue by harry0071** [luffyZh/dynamic-antd-theme#4]
首先，感谢亲提供了这么方便的组件 (づ￣3￣)づ╭❤～
不过，现在的组件只能通过自带的colorPicker选择了颜色后改变theme

我现在有这样一个需求，有以下2个按钮
```javascript
<Button onClick={()=>this.setState(color: 'red')}>点击变红色</Button>
<Button onClick={()=>this.setState(color: 'green')}>点击变绿色</Button>
```

能否给该组件填加个props，可以通过手动传入的颜色来改变theme，比如
```javascript
<DynamicAntdTheme customColor={this.state.color} />
```

这样，不单单只能通过colorPicker修改颜色了，也能通过手动传颜色值改变颜色 😇

**Comment by luffyZh** [comment]
@harry0071 那是否还需要colorPicker 组件？就是目前这个组件的表象是一个颜色选择器，如果你希望在此基础之上只是增加一个属性就是通过传入的颜色变化也可以改变应该是可以的，如果你不想要这个选择器那可能需求就不一样了～可以更详细的沟通一下～

**Comment by harry0071** [comment]
我觉得你应该把colorPicker抽离出来，colorPicker可以让用户选择yarn add后import，也可以选择不使用colorPicker

![1_28WYXtegc-OlYDF-DaJQ8A](https://user-images.githubusercontent.com/22497777/61440464-2eec8b80-a976-11e9-82f3-a27e6bfdb798.png)

如上图所示，colorPicker只负责挑选颜色，不直接改变theme
只有当点击【Change Theme】按钮后，才换肤

我的想法是这样的：
yarn add react-color //拾色器非必须；用户可以通过拾色器选取颜色，也可以不add拾色器 直接手动传入颜色
yarn add dynamic-antd-theme

```javascript
...
import { SketchPicker } from 'react-color';
import DynamicAntdTheme from 'dynamic-antd-theme';
...

<div className='theme-container'>

  <DynamicAntdTheme customColor={this.state.color} />

 <SketchPicker
  onChange={ value=>this.setState({pickerColor: value}) }
   />

<Button onClick={()=>this.setState({color: this.state.pickerColor})}>theme设置为colorPicker选取的颜色</Button>

<Button onClick={()=>this.setState({color: 'green'})}>theme手动设置为绿色</Button>

</div>
```

不知道我是否描述清楚了 😂

**Comment by luffyZh** [comment]
@harry0071 嗯，描述清楚了，哈哈，当时我这边考虑的是
 - 一方面，如果抽离出来，可能这个插件就需要额外安装react-color-picker这种东西，毕竟大部分的场景还都是需要一个picker的，包括antd官网也是如此。
 - 另一方面，如果通过参数传值的模式，也就是字符串，那么就必须控制输入的格式，如果输入的不是一个合法的color，那么这个组件就会报错，可能体验就不是很好了。
像你这种其实可以通过其他方法来简单fix一下，我给你暴露出一个方法，你调用那个方法就行了～哈哈，这个确实没考虑到。
<img width="789" alt="图片" src="https://user-images.githubusercontent.com/17840558/61443259-ba1c5000-a97b-11e9-98c2-e47a56c90732.png">

<img width="561" alt="图片" src="https://user-images.githubusercontent.com/17840558/61443279-c0aac780-a97b-11e9-8fb7-306809bfb5ad.png">
这样就可以满足你的需求了～你觉得如何？

**Comment by harry0071** [comment]
可以 👍👍👍

其实我之所以会提这个issue，是因为我有这样一个需求
```javascript
<Radio.Group>
    <Radio value="blue">男生</Radio>
    <Radio value="pink">女生</Radio>
 </Radio.Group>

//选为男生时，theme变成蓝色调；选为女生时，theme变为粉色调
//因此需要手动设置颜色，而不是直接用colorPicker
```

**Comment by luffyZh** [comment]
@harry0071 已发布，更新到0.3.0就行了～谢谢支持～
<img width="1035" alt="图片" src="https://user-images.githubusercontent.com/17840558/61444386-e20cb300-a97d-11e9-9c69-a57234aed2a4.png">

**Comment by harry0071** [comment]
谢谢😘

话说这个组件只能改变primaryColor吗？[https://antd-live-theme.firebaseapp.com/](https://antd-live-theme.firebaseapp.com/) 它可以改变其他的color

**Comment by luffyZh** [comment]
@harry0071 目前改变的事primary以及与primary的主色系，包含hover，bg，active等等，这个demo里面分的太细了会容易出现主色是红色，然后文字是蓝色，然后hover的时候又是红色的问题。哈哈，我觉得目前这个算是适应大部分场景了
