### ISSUE TITLE
单选框样式没有生效

### ISSUE THREAD

**Issue by a758801405** [luffyZh/dynamic-antd-theme#40]
![image](https://user-images.githubusercontent.com/13042895/99533883-88891e00-29e1-11eb-9f5c-bc4e1a816904.png)

**Comment by luffyZh** [comment]
@a758801405 非常感谢反馈，已修复，更新到最新版
![图片](https://user-images.githubusercontent.com/17840558/99866681-1e919400-2bee-11eb-892d-5daf3decdc8f.png)
