### ISSUE TITLE
antd V4.10版本输入框边框颜色未生效

### ISSUE THREAD

**Issue by alienzhangyw** [luffyZh/dynamic-antd-theme#47]
如图，Button边框颜色正常变化，Search依然是默认主题
![image](https://user-images.githubusercontent.com/58874541/105966726-fd529580-60bf-11eb-993c-575936e76ad0.png)

应该是优先级的问题，前面多了一个类选择
![image](https://user-images.githubusercontent.com/58874541/105966840-21ae7200-60c0-11eb-83b6-eb78faed8ac4.png)

其他类型的input也有同样的问题

**Comment by luffyZh** [comment]
@alienzhangyw 非常感谢，已修复，请更新到最新，有问题随时提。
![图片](https://user-images.githubusercontent.com/17840558/106105800-88df2b80-617f-11eb-9cfc-9265ac46372c.png)

**Comment by alienzhangyw** [comment]
![image](https://user-images.githubusercontent.com/58874541/106130330-2e07fd00-619c-11eb-91a4-4b0bbc8da05f.png)
分页器的边框颜色也有问题
