### ISSUE TITLE
antd V4.10 表格组件所有颜色都未生效

### ISSUE THREAD

**Issue by alienzhangyw** [luffyZh/dynamic-antd-theme#48]
包括选择框、已选行、分页等颜色均未能改变

另外树控件的颜色可能也没有生效，至少已选项目的背景色是没变化的，其他我没试过

**Comment by luffyZh** [comment]
@alienzhangyw 好的，他们经常大版本更新就乱改css classname，感谢，找时间一一修复，修复好了告诉你。

**Comment by alienzhangyw** [comment]
> @alienzhangyw 好的，他们经常大版本更新就乱改css classname，感谢，找时间一一修复，修复好了告诉你。

嗯嗯，其实你可以把demo换成最新版的antd就可以一次性试出哪些组件有问题了。

**Comment by alienzhangyw** [comment]
> @alienzhangyw 好的，他们经常大版本更新就乱改css classname，感谢，找时间一一修复，修复好了告诉你。

我研究了一下，也有可能是我这边的问题。
我使用了webpack4打包以及react的lazyload，最后生成的html文件header里，dynamic-antd-theme的样式夹杂在antd样式的中间，所以同等权重下前面的被后面的覆盖了。
如何保证dynamic-antd-theme写入的样式保持在最后？
是否能更改写入样式的方式和位置？
https://github.com/luffyZh/dynamic-antd-theme/blob/ba762e9ecd04a2ed19a9bf78145e42db13c6f5b4/src/core/util.js#L150

最简单的方式是改写到body里

**Comment by luffyZh** [comment]
是说你的antd表格是用lazy异步加载的是吗，emm，我了解了。有机会我尝试一下，最简单的事放到body里，但是不优雅，我想想其他解法看看。其实你的这种场景就是你在异步加载完成之后手动调整 css 的顺序，这样是最容易的
| |
周公子
|
|
zhoudeyou945@126.com
|


签名由网易邮箱大师定制


在2021年02月1日 14:50，alienzhangyw<notifications@github.com> 写道：

@alienzhangyw 好的，他们经常大版本更新就乱改css classname，感谢，找时间一一修复，修复好了告诉你。

我研究了一下，也有可能是我这边的问题。
我使用了webpack4打包以及react的lazyload，最后生成的html文件header里，dynamic-antd-theme的样式夹杂在antd样式的中间，所以同等权重下前面的被后面的覆盖了。
如何保证dynamic-antd-theme写入的样式保持在最后？
是否能更改写入样式的方式和位置？
https://github.com/luffyZh/dynamic-antd-theme/blob/ba762e9ecd04a2ed19a9bf78145e42db13c6f5b4/src/core/util.js#L150

最简单的方式是改写到body里

**Comment by alienzhangyw** [comment]
我现在是用在页面加入DOM变动观察器来解决的，当检测到head子节点变化时，重新将styleNode放到最后去。

```
// 保证动态主题颜色的样式在document.head最后
const styleObserver = new MutationObserver(() => {
  const styleNode = document.getElementById('dynamic_antd_theme_custom_style');
  if (styleNode && document.head.lastElementChild !== styleNode) {
      document.head.append(styleNode);
  }
});
styleObserver.observe(document.head, { childList: true });
```

这样就解决了绝大部分的问题。
但是依然有个别样式没有生效，比如这个：
![image](https://user-images.githubusercontent.com/58874541/107001745-22808b80-67c5-11eb-8c6d-b26f2b890e57.png)
我看你源码是有这个样式的，但是这里似乎并没有写到style里去。而且浏览器的devtool里对style节点内容的显示有长度限制，后面都变成省略号...了，无法查看是不是有写入。
![image](https://user-images.githubusercontent.com/58874541/107002150-c4a07380-67c5-11eb-95b9-eff687c33ad7.png)

**Comment by luffyZh** [comment]
@alienzhangyw 好的好的，看到了，dom观察期的方法很不错之前有个微服务问题就是这么解决的，正好放假了，明天修复
