### ISSUE TITLE
antd v4.12.3 Submenu title 被选中时候 属性值中 title 颜色未改变

### ISSUE THREAD

**Issue by ShirleyZmj** [luffyZh/dynamic-antd-theme#49]

**Comment by luffyZh** [comment]
@ShirleyZmj  非常感谢，已修复，请更新最新版
<img width="733" alt="图片" src="https://user-images.githubusercontent.com/17840558/109780989-7c4c6800-7c42-11eb-8667-af073c118464.png">

<img width="765" alt="图片" src="https://user-images.githubusercontent.com/17840558/109782412-d3067180-7c43-11eb-86eb-edcd9d6f8caf.png">
