### ISSUE TITLE
官方更新了Button组件，type="danger"的样式，希望作者也同步下

### ISSUE THREAD

**Issue by harry0071** [luffyZh/dynamic-antd-theme#5]
antd官方在v3.20.4更新了type="danger"的样式，希望作者能同步下。
新的危险按钮背景色是红色，字体是白色

![20190806171518.jpg](https://i.loli.net/2019/08/06/lsMFViE1GgjApfZ.jpg)

### 旧的危险按钮，如果用dynamic-antd-theme设置主题色为红色后，hover时就看不到文字了(因为文字也是红色)_(:зゝ∠)_

**Comment by luffyZh** [comment]
@harry0071 v0.3.2，已修复，谢谢反馈～也有可能其他的danger类型也有问题，到时候出现了再说吧。
