### ISSUE TITLE
themeChangeCallback 可以把主题色相关配色都返回不？

### ISSUE THREAD

**Issue by ShirleyZmj** [luffyZh/dynamic-antd-theme#50]
shadow color, active color, hover color

**Comment by luffyZh** [comment]
@ShirleyZmj 之前暴露过一个api，可以通过计算返回的，不过被我隐藏了。
这边有两个方案：
1 - 在themeChangeCallback里把所有颜色返回
2 - 一个通用的方法，在里面再次计算一下
你看看哪个更合适

**Comment by luffyZh** [comment]
@ShirleyZmj 
已经都返回，可以更新最新版使用，非常感谢。
<img width="739" alt="图片" src="https://user-images.githubusercontent.com/17840558/109780108-a3566a00-7c41-11eb-9630-79dc7f972916.png">
