### ISSUE TITLE
第一次打开站点时没有应用primaryColor（该属性设置未起到作用）

### ISSUE THREAD

**Issue by alienzhangyw** [luffyZh/dynamic-antd-theme#52]
根据源码：
https://github.com/luffyZh/dynamic-antd-theme/blob/ba762e9ecd04a2ed19a9bf78145e42db13c6f5b4/src/dynamic-antd-theme.js#L35-L46
组件加载的时候没有使用设置的primaryColor属性去设置颜色，只是更改了picker显示的颜色。

而用户第一次打开站点的时候，localeStorage里是没有颜色的键值的，所以不会调用到changeThemeColor修改主题颜色。

修改建议：
在storageColor为空时使用primaryColor为参数调用changeThemeColor函数。

**Comment by luffyZh** [comment]
没太懂，可以给一个实例截图说明一下，或者直接提一个PR。

**Comment by alienzhangyw** [comment]
> 没太懂，可以给一个实例截图说明一下，或者直接提一个PR。

我是这样用的：
![image](https://user-images.githubusercontent.com/58874541/109897763-26bd9d00-7cce-11eb-95df-4f5da32d622f.png)
如果是第一次打开站点，localeStorage里是没有‘smt-theme-color’这个键的，实际的效果是这样：
![image](https://user-images.githubusercontent.com/58874541/109897977-769c6400-7cce-11eb-9aaa-3f0fe45999f7.png)
只有你的Colorpicker上显示的颜色变成了我设置的#00529C，右边的icon颜色（即站点实际的主题颜色）依然是antd的默认值#1890FF。检查HTML里也并没有写入修改主题颜色的style。
所以DynamicAntdTheme传入的primaryColor属性实际上是没起到作用的，代码里并没有使用这个值去changeAntdTheme。
