### ISSUE TITLE
Does this can change the fontSize of the whole website?

### ISSUE THREAD

**Issue by xmchenlx** [luffyZh/dynamic-antd-theme#76]
Does this can change the fontSize of the whole website through the specific variable?

**Comment by luffyZh** [comment]
看起来是可以的，我这边在浏览器简单尝试了一下，你可以通过 cssVar 传递如下的参数，举例子所有的文字都改：
```js
const cssVar = `
* {
 font-size: 14px
}
`
```
效果应该如下图所示：

![image](https://user-images.githubusercontent.com/17840558/124437516-b91f9b80-dda9-11eb-93bb-9003d62e1714.png)

**Comment by xmchenlx** [comment]
更改颜色我没有填写<DynamicAntdTheme/>，它可以默认更改所有组件，但携带参数的话组件应该写在哪里？也是直接写<DynamicAntdTheme/>，组件不需要包含在页面外面一级吗？我在example示例中没有看到类似的例子
