### ISSUE TITLE
typescript定义没有更新

### ISSUE THREAD

**Issue by alienzhangyw** [luffyZh/dynamic-antd-theme#99]
changeAntdTheme的定义没有更新

**Comment by luffyZh** [comment]
@alienzhangyw 感谢，已经更新

**Comment by alienzhangyw** [comment]
![image](https://user-images.githubusercontent.com/58874541/167594285-3851a2af-5f80-4a2a-a4d3-a750a334fbd0.png)
更新到最新版和React18之后有问题了
